### ISSUE TITLE
maybe a typo in Seat class

### ISSUE THREAD

**Issue by safanaj** [scottwakeling/seat-inspect#5]
I discovered just now a weird python3 feature, at [this line](https://github.com/spanezz/seat-inspect/blob/master/seat-inspect#L95) the name "seat" is used.
I guess a typo cause seems not used elsewhere.
Seems that inside a class  the "classname"-lowercase refer at "self" if not used as local variable.

**Comment by spanezz** [comment]
On Fri, Feb 13, 2015 at 01:22:00AM -0800, Marco wrote:

> I discovered just now a weird python3 feature, at this line the name "seat" is
> used.
> I guess a typo cause seems not used elsewhere.
> Seems that inside a class the "classname"-lowercase refer at "self" if not used
> as local variable.

Thanks, good catch!

It was indeed a typo, or rather a leftover from a previous refactoring.

There is no magic use of lowercase classname, though: line 433 :

  for seat in (Seat(*x) for x in login_iface.ListSeats()):

actually sets a 'seat' variable in the module namespace, and the line
you pointed at was reading from that. Python scoping can be rather
surprising :/ I'd really like to keep seat-inspect a single-source file,
but splitting classes into separate source can be a way of avoid this
kind of name pollution.

I've now improved things a bit by putting the main body into a separate
function: since function have their own local namespace, they do not
pollute the module namespace by default.

Enrico

## 

GPG key: 4096R/E7AD5568 2009-05-08 Enrico Zini enrico@enricozini.org

**Comment by spanezz** [comment]
I had fixed this but forgot to close it.
